---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    types: [ file, yaml ]
  - id: check-yaml
    args: [ --allow-multiple-documents ]
  - id: check-added-large-files
    args: [ --maxkb=768 ]

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.11.0.1
  hooks:
  - id: shellcheck
